[package]
name = "lazy-socket"
version = "0.1.0"
authors = ["Douman <douman@gmx.se>"]
description = "Low level Raw Socket API. WIP"
repository = "https://github.com/DoumanAsh/lazy-socket.rs"
documentation = "https://docs.rs/crate/lazy-socket/"
license = "MIT"

[dependencies]

[target."cfg(unix)".dependencies]
libc = "^0.2.20"
